name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5

      - name: Cache SBT coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: sbt-coursier-cache

      - name: Scalafmt
        run: sbt scalafmtAll scalafmtSbt

      - name: Tests
        run: sbt scripted